import type { Content } from '@models/content';

export const mockContents: Content[] = [
  {
    id: 1,
    title: '서울의 밤 추적자',
    type: 'movie',
    releaseYear: 2024,
    ageRating: '15',
    runningTime: '2시간 03분',
    description: '야간 순찰대 형사와 데이터 분석가가 연쇄 사건을 쫓으며 거대한 음모를 파헤친다.',
    genres: ['스릴러', '범죄'],
    cast: ['정민우', '서하나', '김태연'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-1/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-1/1600/900',
  },
  {
    id: 2,
    title: '여름의 코드',
    type: 'series',
    releaseYear: 2025,
    ageRating: '12',
    runningTime: '시즌 1 · 8부작',
    description: '해커톤 팀이 스타트업을 만들며 우정, 갈등, 성장을 겪는 청춘 드라마.',
    genres: ['드라마', '청춘'],
    cast: ['유시온', '박서진', '이도윤'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-2/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-2/1600/900',
  },
  {
    id: 3,
    title: '미드나잇 셰프',
    type: 'variety',
    releaseYear: 2023,
    ageRating: 'ALL',
    runningTime: '에피소드 12개',
    description: '밤 12시에만 열리는 푸드 스튜디오에서 셰프들이 미션형 요리 대결을 펼친다.',
    genres: ['예능', '요리'],
    cast: ['박주형', '윤서아'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-3/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-3/1600/900',
  },
  {
    id: 4,
    title: '파동의 숲',
    type: 'animation',
    releaseYear: 2024,
    ageRating: 'ALL',
    runningTime: '1시간 42분',
    description: '소리를 시각화하는 능력을 가진 아이가 숲의 비밀을 찾아 떠나는 판타지 애니메이션.',
    genres: ['애니메이션', '판타지'],
    cast: ['한소율', '남지후'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-4/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-4/1600/900',
  },
  {
    id: 5,
    title: '라스트 스테이션',
    type: 'movie',
    releaseYear: 2022,
    ageRating: '19',
    runningTime: '2시간 11분',
    description: '폐쇄된 기차역에서 시작된 실종 사건이 도시 전체를 뒤흔드는 미스터리 스릴러.',
    genres: ['미스터리', '스릴러'],
    cast: ['최도현', '배나리'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-5/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-5/1600/900',
  },
  {
    id: 6,
    title: '코발트 리그',
    type: 'series',
    releaseYear: 2024,
    ageRating: '15',
    runningTime: '시즌 2 · 10부작',
    description: '가상 스포츠 리그를 둘러싼 선수들의 경쟁과 정치적 음모를 다룬 SF 드라마.',
    genres: ['SF', '드라마'],
    cast: ['문재인', '이한솔', '오준혁'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-6/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-6/1600/900',
  },
  {
    id: 7,
    title: '한강 러너스',
    type: 'variety',
    releaseYear: 2025,
    ageRating: '12',
    runningTime: '에피소드 16개',
    description: '러닝 크루들이 미션을 수행하며 도시 곳곳의 이야기를 발굴하는 리얼 버라이어티.',
    genres: ['예능', '스포츠'],
    cast: ['김민성', '차은비'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-7/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-7/1600/900',
  },
  {
    id: 8,
    title: '제로 그래비티 스쿨',
    type: 'animation',
    releaseYear: 2023,
    ageRating: 'ALL',
    runningTime: '시즌 1 · 12부작',
    description: '우주 기숙학교에서 벌어지는 사고를 해결하는 학생들의 모험과 우정을 그린다.',
    genres: ['애니메이션', 'SF'],
    cast: ['정채린', '송재우'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-8/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-8/1600/900',
  },
  {
    id: 9,
    title: '블라인드 월',
    type: 'movie',
    releaseYear: 2021,
    ageRating: '15',
    runningTime: '1시간 56분',
    description: '한 통의 익명 메시지로 시작된 심리 게임, 누구도 믿을 수 없는 밀실 서스펜스.',
    genres: ['스릴러', '심리'],
    cast: ['노지환', '강유빈'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-9/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-9/1600/900',
  },
  {
    id: 10,
    title: '오후 4시의 편지',
    type: 'series',
    releaseYear: 2022,
    ageRating: '12',
    runningTime: '시즌 1 · 6부작',
    description: '매일 오후 4시에 도착하는 의문의 편지가 사람들의 인생을 바꾸는 휴먼 드라마.',
    genres: ['드라마', '감성'],
    cast: ['한지연', '백정우'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-10/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-10/1600/900',
  },
  {
    id: 11,
    title: '우주정원 307',
    type: 'animation',
    releaseYear: 2025,
    ageRating: 'ALL',
    runningTime: '1시간 35분',
    description: '황폐한 행성에서 식물을 키우는 소년이 희망의 씨앗을 퍼뜨리는 이야기.',
    genres: ['애니메이션', '가족'],
    cast: ['심다온', '진민호'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-11/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-11/1600/900',
  },
  {
    id: 12,
    title: '타임 캡슐 라이브',
    type: 'variety',
    releaseYear: 2024,
    ageRating: '12',
    runningTime: '에피소드 10개',
    description: '과거 히트곡을 현대적으로 재해석해 무대를 꾸미는 음악 프로젝트.',
    genres: ['예능', '음악'],
    cast: ['류예린', '최호진'],
    thumbnailUrl: 'https://picsum.photos/seed/netflix-card-12/640/360',
    heroUrl: 'https://picsum.photos/seed/netflix-hero-12/1600/900',
  },
];
